import { Category, Sound } from "@/types";

export const sounds: Sound[] = [
  {
    id: 1,
    title: "Oh no no no no",
    duration: 10.06,
    plays: 1500000,
    downloads: 250000,
    category: { id: 1, name: "Nhạc nền" },
    url: "/gophim.mp3",
  },
  {
    id: 2,
    title: "Into the night",
    duration: 6.01,
    plays: 890000,
    downloads: 120000,
    category: { id: 2, name: "Nhạc game" },
    url: "/whoosh.mp3",
  },
  {
    id: 3,
    title: "Emotional damage",
    duration: 10.06,
    plays: 2100000,
    downloads: 450000,
    category: { id: 3, name: "Âm thanh thiên nhiên" },
    url: "/gophim.mp3",
  },
  {
    id: 4,
    title: "Running in the 90s",
    duration: 10.06,
    plays: 750000,
    downloads: 95000,
    category: { id: 4, name: "Tiếng động vật" },
    url: "/gophim.mp3",
  },
  {
    id: 5,
    title: "Running in the 90s",
    duration: 10.06,
    plays: 750000,
    downloads: 95000,
    category: { id: 4, name: "Tiếng động vật" },
    url: "/gophim.mp3",
  },
  // {
  //   id: 6,
  //   title: "Running in the 90s",
  //   duration: 10.06,
  //   plays: 750000,
  //   downloads: 95000,
  //   category: { id: 4, name: "Tiếng động vật" },
  //   url: "/gophim.mp3",
  // },
  // {
  //   id: 7,
  //   title: "Running in the 90s",
  //   duration: 10.06,
  //   plays: 750000,
  //   downloads: 95000,
  //   category: { id: 4, name: "Tiếng động vật" },
  //   url: "/gophim.mp3",
  // },
  // {
  //   id: 8,
  //   title: "Running in the 90s",
  //   duration: 10.06,
  //   plays: 750000,
  //   downloads: 95000,
  //   category: { id: 4, name: "Tiếng động vật" },
  //   url: "/gophim.mp3",
  // },
  // {
  //   id: 9,
  //   title: "Running in the 90s",
  //   duration: 10.06,
  //   plays: 750000,
  //   downloads: 95000,
  //   category: { id: 4, name: "Tiếng động vật" },
  //   url: "/gophim.mp3",
  // },
  // {
  //   id: 10,
  //   title: "Running in the 90s",
  //   duration: 10.06,
  //   plays: 750000,
  //   downloads: 95000,
  //   category: { id: 4, name: "Tiếng động vật" },
  //   url: "/gophim.mp3",
  // },
];

export const categories: Category[] = [
  { id: 1, name: "Nhạc nền" },
  { id: 2, name: "Nhạc game" },
  { id: 3, name: "Âm thanh thiên nhiên" },
  { id: 4, name: "Tiếng động vật" },
  { id: 5, name: "Hiệu ứng âm thanh" },
  { id: 6, name: "Tiếng cười" },
  { id: 7, name: "Âm thanh hoạt hình" },
  { id: 8, name: "Nhạc phim" },
  { id: 9, name: "Tiếng người" },
  { id: 10, name: "Âm thanh thể thao" },
];

export const PATHS = {
  home: "/",
  searchResults: "/ket-qua-tim-kiem",
  categories: "/the-loai",
  login: "/login",
  signup: "/signup",
  account: "/account",
  admin: "/admin",
  adminCategories: "/admin/categories",
  adminSounds: "/admin/sounds",
  viral: "/am-thanh-viral",
  new: "/am-thanh-moi",
};

export const PAGINATION = {
  pageSize: 10,
};
